package vn.edu.fpt.SE2034_SWP391_G5.enums;

public enum NotificationType {
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_NEW,
    CHECKIN_DONE,
    MEDICAL_RECORD_CREATED,
    INVOICE_CREATED,
    INVOICE_PAID,
    SCHEDULE_ASSIGNED
}
